#!/bin/bash
clear
[[ -e /home/versTO ]] && rm /home/versTO
wget -P /home http://ssh-plus.tk/script/versTO > /dev/null 2>&1
[[ -f "/home/versTO" ]] && {
	vrs1=$(sed -n '1 p' /bin/versTO| sed -e 's/[^0-9]//ig')
    vrs2=$(sed -n '1 p' /home/versTO | sed -e 's/[^0-9]//ig')
	[[ "$vrs1" != "$vrs2" ]] && mv /home/versTO /tmp/att
}
